### ISSUE TITLE
Mention read:false in README.md

### ISSUE THREAD

**Issue by Frank3K** [pgilad/gulp-sitemap#14]
In the [gulpfile.js](https://github.com/pgilad/gulp-sitemap/blob/aea6f893fed9263be4e9f8857e59cb15a792bdca/gulpfile.js) I saw that `{ read: false }` is passed as argument to `gulp.src()`. I did not know about this functionality and I think it would be an improvement if this would be included in  the example in `README.md`.

**Comment by pgilad** [comment]
Great thought, PR is welcome!
