### ISSUE TITLE
Getting template URLs instead of URLs

### ISSUE THREAD

**Issue by ahsan115533** [pgilad/gulp-sitemap#19]
When I run gulp-sitemap, I'm getting list of all my html pages in sitemap.xml. But these are of no use, what I want is proper URLs which are defined in my app.js against these html pages. How to get exact URLs which open in the browser through gulp-sitemap

**Comment by pgilad** [comment]
What you want to do, is use a property called `mappings` (https://github.com/pgilad/gulp-sitemap#mappings) and use a `pages` pattern that will match the relevant pages, and set the `geLoc` function to modify/trim the url to show.
