### ISSUE TITLE
.com removed

### ISSUE THREAD

**Issue by MatthewVance** [pgilad/gulp-sitemap#21]
First off, thanks for the great plugin. I wanted to open this issue in case this is a minor bug. 

The .com portion of my domain is also getting removed when using the remove extension example code. I'm not sure if I'm doing something wrong in my `gulpfile.js` or if this is a bug. 

My setup is:

```
gulp.task('sitemap', function () {
  return gulp.src(['./dist/**/*.html','!./dist/exceptions/*','!./dist/google*.html'], {
    read: false
  })
    .pipe(plugins.sitemap({
      siteUrl: 'https://vanceauto.com',
      getLoc: function(siteUrl, loc, entry) {
          return loc.substr(0, loc.lastIndexOf('.')) || loc; // Removes the file extension
      }
  }))
    .pipe(gulp.dest('./dist/'));
});
```

The generated `sitemap.xml` looks like:

```
<url>
<loc>https://domain</loc>
<lastmod>2016-11-13T04:20:07.000Z</lastmod>
</url>
<url>
<loc>https://domain.com/inventory</loc>
<lastmod>2016-11-13T04:20:07.000Z</lastmod>
</url>
```

**Comment by pgilad** [comment]
Yeah, that substr replacement is wrong. Use:
`getLoc(siteUrl, loc, entry) {
  return loc.replace(/\.\w+$/, '');
`

**Comment by MatthewVance** [comment]
Thank for the quick response. That fixed it.
