### ISSUE TITLE
How to ignore some files?

### ISSUE THREAD

**Issue by boiciuc** [pgilad/gulp-sitemap#22]
Is there a way to ignore some files?

I use email.html as an html email template for a simple php form, in the root of the project (same folder as index.html) and i don`t want that file to be added in the sitemap.

**Comment by pgilad** [comment]
The way to ignore them is to not feed them into the gulp pipeline. So you can use a glob to ignore them in your `gulp.src` and you can use use some plugins (`gulp-ignore` for example) to filter them out during the stream
