### ISSUE TITLE
Using PHP files as index

### ISSUE THREAD

**Issue by nickmistretta9** [pgilad/gulp-sitemap#26]
Great job on this plugin I am loving how it works so far. The only issue I am running into is that I generally use php files instead of html, so when I am building the sitemap, I am getting domain.com/index.php instead of just domain.com. I have tried to use your regex pattern in the loc.replace function at first just trying to remove the .com, but I can't get it to just apply to the one url, it does it to all of them. I also tried to do it with mappings, but it is also not working. Here is my code:
```
.pipe(sitemap({
	siteUrl:siteUrl,
	mappings: [{
		pages: ['dev/index.php'],
		getLoc(siteUrl, loc, entry) {
			return loc.replace(/\.\w+$/, '');
		}
	}]
}))
```
Is there any support for php files in the works or is there a better way to accomplish this? Any help would be greatly appreciated.

**Comment by pgilad** [comment]
Hey, sorry for the late reply, I added a passing test case to show how it's done, let me know if I can help further.. https://github.com/pgilad/gulp-sitemap/commit/b3f726ea943b86b7877618df7ed83ff56459f853#diff-e54d06e10f81bed55da4d1350d547a51R251
