### ISSUE TITLE
Error in plugin "gulp-sitemap"

### ISSUE THREAD

**Issue by euro** [pgilad/gulp-sitemap#32]
Environment:
node -v v10.15.3
npm -v 6.4.1
gulp -v CLI version 2.0.1 / Local version 4.0.0

I created a clean test with 3 minimal html files (index, about and 404) and this gulpfile:

```js
var gulp = require('gulp');
var sitemap = require('gulp-sitemap');

gulp.task('sitemap', function () {
    gulp.src('*.html', {
            read: false
        })
        .pipe(sitemap({
            siteUrl: 'http://www.test.com'
        }))
        .pipe(gulp.dest('/'));
});

exports.default = sitemap;
```

My console reports an error:
```sh
sitemap $ gulp
[00:17:43] Using gulpfile ~/WebServer/sitemap/gulpfile.js
[00:17:43] Starting 'default'...
[00:17:43] 'default' errored after 4.4 ms
[00:17:43] Error in plugin "gulp-sitemap"
Message:
    siteUrl is a required param
Details:
    domain: [object Object]
    domainThrown: true

sitemap $
```

**Comment by pgilad** [comment]
I have no idea why this is happening, I can reproduce this locally as well. It seems to me like `gulp` transforms the imported file and binds it, thus it never receives the options. Probably something to do with new gulp `4+` version?

**Comment by euro** [comment]
I can confirm it works fine with 3.9.1 so that's what I'd guess.

**Comment by pgilad** [comment]
I'll try to debug it, but will appreciate any help. I've checked other plugins, it doesn't seem like anything needed to change for version 4 😿

**Comment by euro** [comment]
I also tried this alternative gulp 4 syntax and it also reports the same error.
```js
function sitemap (done) {
  gulp.src('*.html', {
      read: false
    })
    .pipe(sitemap({
      siteUrl: 'http://www.test.com'
    }))
    .pipe(gulp.dest('/'))
    done();
}
```

**Comment by pgilad** [comment]
I'm guessing `gulp-cli` transforms the file somehow, causing a change in binding functions. I'm not a gulp user anymore so not up-to-date with all recent changes, but very sad that version 4 broke this plugin

**Comment by euro** [comment]
Im not so sure thats it. Im running that same 2.0.1 CLI with a 3.9.1 Gulp on another project with this plugin and its working. I'm going to take a look and try to strip it down to its bare-bones to debug but this is way over my head.  👍

**Comment by pgilad** [comment]
Ok this works for me:
```js
var { src, dest } = require('gulp');
var sitemap = require('gulp-sitemap');

exports.default = function() {
    const plugin = sitemap({ siteUrl: 'http://www.test.com' });

    return src('src/*.html', {
        read: false
    })
        .pipe(plugin)
        .pipe(dest('dist/'));
}
```

Moving html files to `src` and outputting to `dist`

**Comment by pgilad** [comment]
Ok this works too:
```js
const { src, dest } = require('gulp');
const sitemap = require('gulp-sitemap');

function generateSitemap() {
    const plugin = sitemap({ siteUrl: 'http://www.test.com' });

    return src('src/*.html', {
        read: false
    })
        .pipe(plugin)
        .pipe(dest('dist/'));
}

exports.sitemap = generateSitemap;
```

Then run `gulp sitemap`

Anyway it was due to a bad configuration in `gulpfile.js`, I consider this our own mis-understanding of how gulp 4 works :)

**Comment by euro** [comment]
Confirmed 🥇 you rock, thanks!
