### ISSUE TITLE
How to exclude pages that contain the noindex or nofollow?

### ISSUE THREAD

**Issue by TiagoDeSousa** [pgilad/gulp-sitemap#33]
Is there a way to to exclude pages that contain noindex or nofollow? I have a few pages that have those tags in the meta content and I don't want to include them in sitemap.xml file.

**Comment by TheDancingCode** [comment]
I think it would be a nice addition to this plugin to provide an option to exclude pages containing the `noindex` value in the `robots` meta tag. I don't see how the `nofollow` value is relevant for the sitemap, however.

**Comment by pgilad** [comment]
> would a PR be welcome?

An opt-in option would be great
