### ISSUE TITLE
Suggestion: verbose option

### ISSUE THREAD

**Issue by klwemu** [pgilad/gulp-sitemap#5]
Would be nice to have some informations about the task, at least the number of handled files.
As second level the processed file names.   ... folder/filename

Thx, klaus

**Comment by pgilad** [comment]
if you just want the information about file objects coming through the stream you can use: gulp-using or gulp-debug or gulp-size.

Is that enough or do you need the actual files handled?

A PR is welcomed if you feel this option is needed

**Comment by klwemu** [comment]
It would be enough to have "Files in sitemap: 232" in the console.

2015-02-27 10:02 GMT+01:00 Gilad Peleg <notifications@github.com>:

> if you just want the information about file objects coming through the
> stream you can use: gulp-using or gulp-debug or gulp-size.
>
> Is that enough or do you need the actual files handled?
>
> A PR is welcomed if you feel this option is needed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pgilad/gulp-sitemap/issues/5#issuecomment-76358970>.
>



-- 

Klaus Muckenhuber
Business Developement

https://VISITLEAD.com
0049 7247 50315 - 11

**Comment by pgilad** [comment]
done
