### ISSUE TITLE
Globbed negations ignored

### ISSUE THREAD

**Issue by ScottSmith95** [pgilad/gulp-sitemap#6]
Attempting to remove bower_components and node_modules file's .html files from the sitemap fails.
```
gulp.task('sitemap', function () {
	return gulp.src(['**/*.html', '!node_modules/', '!bower_components/'])
		.pipe(sitemap({
			siteUrl: 'https://scotthsmith.com',
			pages: ['!node_modules/', '!bower_components/']
		}))
		.pipe(gulp.dest('./'));
});
```
Both attempts at removing these source files from the output are unsuccessful.

**Comment by pgilad** [comment]
Ok, 3 options:

1. Try the glob pattern in `gulp.src` like this: `gulp.src(['**/*.html', '!node_modules/**/*', '!bower_components/'**/*])

2. Try the same glob pattern in `pages` property: `pages: ['!node_modules/**/*', '!bower_components/**/*']`

Overall option no.1 should work, and if it doesn't - then there's a problem with `gulp.src` executing the glob. `gulp-sitemap` only handles the files that are passed to it through the stream.

3. Not really an option, but a useful debug tool is to add the plugin `gulp-debug` and add it to the stream immediately after the `gulp.src` so that you can see which files are passed through. This will help you debug.
A link to [gulp-debug](https://github.com/sindresorhus/gulp-debug)

**Comment by ScottSmith95** [comment]
It looks like `gulp.src` needs the following: 
`gulp.src(['**/*.html', '!bower_components/**/*', '!node_modules/**/*'])`

**Comment by pgilad** [comment]
Great, glad to see it works... can this issue be closed?

**Comment by ScottSmith95** [comment]
Yes, thank you.

**Comment by ktamiola** [comment]
Hi there! I am also having some issues with globbed negation!

My task,
`/*
 Sitemap task
*/
gulp.task('build:sitemap', function(callback) {
    return gulp.src(tmpDir+'**/*.html')
    .pipe(debug({title: ' What goes in :'}))
    .pipe(sitemap({
            siteUrl: 'http://www.tamiola.com',
            pages: ['!403.html'] // exclude 4XX and 5XX error pages
    }))
    .pipe(gulp.dest(tmpDir));
});`

the output using pipe debugger

`[00:03:38] Using gulpfile ~/Development/tamiola.com/gulpfile.js
[00:03:38] Starting 'build:sitemap'...
[00:03:38]  What goes in : tmp/403.html
[00:03:38]  What goes in : tmp/404.html
[00:03:38]  What goes in : tmp/index.html
[00:03:38]  What goes in : 3 items
[00:03:38] Finished 'build:sitemap' after 83 ms`

I am trying to exclude 403.html page. Obviously I will have more custom error pages I would like to shut down too.

**Comment by pgilad** [comment]
Hey - your glob negation pattern needs to be something of the sort:
`!**/403.html`.

I would actually suggest not piping it through `gulp.src`, that way you don't waste time on reading files you won't have any action on in the stream.

**Comment by ktamiola** [comment]
Thank you for swift response! I cannot get it to work with  ` !**/403.html`. The **403** is still in the index.

**Comment by pgilad** [comment]
Your main goal should be to not stream the unwanted files (unless you have to). This means mastering glob patterns in `gulp.src`.

If you can create a minimum example repo with the files and gulpfile I can help you get it running

**Comment by ktamiola** [comment]
Dear Gilad! Thank you for your effort! Indeed, piping in the files of interest was the way to go. I have created a relatively obscure globbing pattern:

`'**/!(4*.html|*.css|*.js|*.w*|*.eot|*.svg|*.png|*.ttf|*.jpg|*.jpeg|*.json|*.ico|*.xml)'`

It does work. If only I get some more time I will try to wrap it into something more human-readable :)

**Comment by pgilad** [comment]
If you split your files into folders you will be able to much better ignore them.
Also you can try brace expansion:
`['!**/4*.html', '!**/*.{css,js,w,eot,svg,png,ttf,jpg,jpeg,json,ico,xml}']`

**Comment by ktamiola** [comment]
Thanks @pgilad. All my _css/js/font_ files are organised in the folders, as a matter of fact.
