### ISSUE TITLE
hreflang support

### ISSUE THREAD

**Issue by klwemu** [pgilad/gulp-sitemap#9]
Would be a nice new feature to generate optional also the hreflang tag into the sitemap. To keep it useable I assume same filename in all languages - only different pathes.

def-hreflangs {
  "mydomain.com/ru/", "ru"
  "mydomain.com/de/", "de"
  "mydomain.com/en/", "en"
}

you look wich of them matches for the current file path, and all other hreflangs entries you write into the sitemap.
```html
<url>
  <some other tags>
  <xhtml:link rel="alternate" hreflang="ru" href="http://www.doamin.ru/client/page1.html/"/>
  <xhtml:link rel="alternate" hreflang="en" href="http://www.doamin.en/client/page1.html/"/>
</url>
```

**Comment by osv** [comment]
+1

**Comment by pgilad** [comment]
A PR is highly welcome @klwemu

**Comment by pgilad** [comment]
@osv @klwemu Finally got around to this, and implemented as part of mappings so that languages can be applied to certain pages, or to all (with `*` pattern).

Let me know how it works!

**Comment by osv** [comment]
I ended with own gulp task that read config file and create language support
It some one want my piece of code look here: https://gist.github.com/osv/9266c5d98d1c95b111bd

**Comment by pgilad** [comment]
Great, thanks for the input!
